name: 
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- bzip2=1.0.8
- ca-certificates=2022.12.7
- faker=18.4.0
- greenlet=2.0.2
- keyutils=1.6.1
- krb5=1.20.1
- ld_impl_linux-64=2.40
- libblas=3.9.0
- libcblas=3.9.0
- libedit=3.1.20191231
- libffi=3.4.2
- libgcc-ng=12.2.0
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libgomp=12.2.0
- liblapack=3.9.0
- libnsl=2.0.0
- libopenblas=0.3.21
- libpq=15.2
- libsqlite=3.40.0
- libstdcxx-ng=12.2.0
- libuuid=2.38.1
- libzlib=1.2.13
- ncurses=6.3
- numpy=1.24.3
- openssl=3.1.0
- pandas=2.0.0
- pip=23.0.1
- psycopg=3.1.8
- psycopg-c=3.1.8
- python=3.10.10
- python-dateutil=2.8.2
- python-tzdata=2023.3
- python_abi=3.10
- pytz=2023.3
- readline=8.2
- setuptools=67.6.1
- six=1.16.0
- sqlalchemy=2.0.10
- tk=8.6.12
- typing-extensions=4.5.0
- typing_extensions=4.5.0
- tzdata=2023c
- wheel=0.40.0
- xz=5.2.6

